name: photoboard
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  line_icons: ^0.2.0
  responsive_screen: ^1.0.0
  image_picker: ^0.6.5+3
  path: ^1.6.4
  path_provider: ^1.6.7
  flutter_bloc: ^4.0.0
  avatar_glow: ^1.1.0
  google_fonts: ^1.0.0
  flutter_spinkit: ^4.1.2+1
  cloud_firestore: ^0.13.5
  firebase: ^7.3.0
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  google_sign_in: ^4.4.4
  intl: ^0.16.1
  transformer_page_view: ^0.1.6
  font_awesome_flutter: ^8.8.1
  flushbar: ^1.10.0
  percent_indicator: ^2.1.3
  shared_preferences: ^0.5.6
  page_view_indicators: ^1.3.1
  cached_network_image: ^2.2.0+1
  progress_dialog: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/images/placeholder.jpg
    - assets/images/facebook_logo.png
    - assets/images/ic_launcher_round.png
    - assets/foto1.png

  uses-material-design: true

  
