name: ejemplo_construccion
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"
  

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: 1.0.0

  intro_slider: ^1.0.8

  font_awesome_flutter: ^8.5.0
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  flutter_dotenv: ^2.1.0
  package_info: ^0.4.0
  line_icons: ^0.2.0
  responsive_screen: ^1.0.0
  image_picker:  ^0.6.5+3
  path: ^1.6.4
  path_provider: ^1.6.7
  flutter_bloc: ^3.2.0

  percent_indicator: ^2.1.3
  intl: ^0.16.1
  # dummy package to test https://github.com/NearHuscarl/flutter_login/issues/35
  provider: ^4.0.1
  

  cupertino_icons: ^0.1.2
  avatar_glow: 1.1.0
  table_calendar: ^2.2.3
  google_fonts: 0.2.0
  flutter_spinkit: 4.1.2

  


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
  - assets/foto1.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #assets:
  #- assets/images/foto.png
  #- assets/images/foto2.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
